- name: Create metallb-system Namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: metallb-system
    state: present
    definition:
      metadata:
        labels:
          name: metallb-system

- name: Create metallb-operator OperatorGroup
  kubernetes.core.k8s:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    namespace: metallb-system
    name: metallb-operator
    state: present
    definition:
      metadata:
        name: metallb-operator
        namespace: metallb-system

- name: Create Subscription for metallb-operator
  kubernetes.core.k8s:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: metallb-system
    name: metallb-operator-sub
    state: present
    definition:
      metadata:
        name: metallb-operator-sub
        namespace: metallb-system
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: metallb-operator
        source: "{{ subscription_source }}"
        sourceNamespace: openshift-marketplace

- name: Wait for CSV to be in Succeeded state
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: metallb-system
  register: csv_status
  until: >
    csv_status.resources | selectattr('status.phase', 'equalto', 'Succeeded') | list | length > 0
  retries: 30
  delay: 10

- name: Wait for metallb pod to be created
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: metallb-system
  register: pod_status
  until: pod_status.resources | length > 0
  retries: 30
  delay: 10

- name: Create MetalLB Instance
  kubernetes.core.k8s:
    api_version: metallb.io/v1beta1
    kind: MetalLB
    namespace: metallb-system
    name: nmstate
    state: present
    definition:
      metadata:
        name: metallb
        namespace: metallb-system
      spec: { }
