- name: Create bpfman Namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: bpfman
    state: present
    definition:
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/enforce-version: v1.24
          name: bpfman

- name: Create bpfman OperatorGroup
  kubernetes.core.k8s:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    state: present
    definition:
      metadata:
        name: bpfman-operator
        namespace: bpfman
      spec:
        targetNamespaces:
          - bpfman

- name: Create Subscription for bpfman-operators
  kubernetes.core.k8s:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    state: present
    definition:
      metadata:
        name: bpfman-operator
        namespace: bpfman
      spec:
        channel: alpha
        installPlanApproval: Automatic
        name: bpfman-operator
        source: community-operators
        sourceNamespace: openshift-marketplace

- name: Wait for CSV to be in Succeeded state
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: bpfman
  register: csv_status
  until: >
    csv_status.resources | selectattr('status.phase', 'equalto', 'Succeeded') | list | length > 0
  retries: 30
  delay: 10

- name: Check if ImageContentSourcePolicy is Approved
  ansible.builtin.command: oc get installplan -n bpfman -o jsonpath="{.items[*].status.conditions[?(@.type=='Installed')].status}"
  register: ip_status
  until: ip_status.stdout == "True"
  retries: 30
  delay: 10
  changed_when: false

- name: Wait for bpfman pods to be created
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: bpfman
  register: pod_status
  until: pod_status.resources | length > 0
  retries: 30
  delay: 10

