- name: Include shared ImageContentSourcePolicy tasks
  import_tasks: ../../shared/icsp.yaml

- name: Include shared CatalogSource tasks
  import_tasks: ../../shared/catalogsource.yaml

- name: Install NMState Operator
  import_tasks: install_nmstate_operator.yaml
